apiVersion: v1
kind: Namespace
metadata:
  name: elasticactors
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticactors-operator
  namespace: elasticactors
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticactors-operator
  namespace: elasticactors
rules:
  # -------------------------------------------------------------------------
  # The following are the resources created by the operator,
  # the operator needs to list, watch, and create these resources.
  # -------------------------------------------------------------------------
  - apiGroups:
      - ''
      - 'extensions'
      - 'apps'
      - 'rbac.authorization.k8s.io'
    resources:
      - 'serviceaccounts'
      - 'clusterroles'
      - 'clusterrolebindings'
      - 'secrets'
      - 'configmaps'
      - 'daemonsets'
    verbs:
      - 'list'
      - 'watch'
      - 'create'
  # -------------------------------------------------------------------------
  # The following need to be watched, but not created:
  # * Pods are created by the daemon set.
  # * The custom resource definition is created by the user.
  # -------------------------------------------------------------------------
  - apiGroups:
      - ''
      - 'apiextensions.k8s.io'
    resources:
      - 'pods'
      - 'customresourcedefinitions'
    verbs:
      - 'list'
      - 'watch'
  # -------------------------------------------------------------------------
  # Events are just created but not watched. It's a fire-and-forget operation.
  # -------------------------------------------------------------------------
  - apiGroups:
      - ''
    resources:
      - 'events'
    verbs:
      - 'create'
  # -------------------------------------------------------------------------
  # For the custom resources, the operator needs list, watch, get, update.
  # -------------------------------------------------------------------------
  - apiGroups:
      - 'elasticactors.io'
    resources:
      - 'actorsystems'
    verbs:
      - 'get'
      - 'update'
      - 'list'
      - 'watch'
  # -------------------------------------------------------------------------
  # Below are the permissions are for the agent.
  # The operator needs these permissions to create the agent's cluster role.
  # -------------------------------------------------------------------------
  - apiGroups:
      - ''
    resources:
      - 'componentstatuses'
      - 'endpoints'
      - 'events'
      - 'namespaces'
      - 'nodes'
      - 'pods'
      - 'replicationcontrollers'
      - 'resourcequotas'
      - 'resourcequotas'
      - 'services'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - ''
    resources:
      - 'endpoints'
    verbs:
      - 'create'
      - 'update'
      - 'patch'
  - apiGroups:
      - 'apps'
    resources:
      - 'deployments'
      - 'replicasets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'batch'
    resources:
      - 'jobs'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'extensions'
    resources:
      - 'deployments'
      - 'ingresses'
      - 'replicasets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - "apps.openshift.io"
    resources:
      - "deploymentconfigs"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elasticactors-operator
  namespace: elasticactors
subjects:
  - kind: ServiceAccount
    name: elasticactors-operator
    namespace: elasticactors
roleRef:
  kind: ClusterRole
  name: elasticactors-operator
  apiGroup: rbac.authorization.k8s.io